version: 0.1
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - npm run-script build
  post_build:
    commands:
      - aws s3 cp build s3://xqn-cicd-test --recursive --acl public-read